name: Deploy Lambda

on:
  # push:
  #   branches:
  #     - develop

  workflow_dispatch:
    inputs:
      #Input to select the action.
      INPUT_FUNCTION:
        description: 'Select which Lambda function'
        required: true
        type: choice
        options:
          - none
          - function-1
          - function-2
          - function-3
      #Input to run tests.
      INPUT_ACTION:
        description: 'Select action'
        required: true
        default: build-and-deploy
        type: choice
        options:
          - build
          - build-and-deploy
      #Input to run tests.
      RUN_TESTS:
        description: 'Run unit & coverage tests?'
        required: true
        default: false
        type: choice
        options:
          - true
          - false
      #Input to scan with sonarqube.
      SONAR_SCAN_ENABLE:
        description: 'Scan with sonarqube?'
        required: true
        default: false
        type: choice
        options:
          - true
          - false

permissions:
  id-token: write # Allow the workflow to request an OIDC token for AWS authentication.
  contents: read

env:
  INPUT_FUNCTION: ${{ github.event.inputs.INPUT_FUNCTION }}
  INPUT_ACTION: ${{ github.event.inputs.INPUT_ACTION || 'build-and-deploy' }} #Default needed since the workflow will not use the input default when run on-push.
  SONAR_SCAN_ENABLE: ${{ github.event.inputs.SONAR_SCAN_ENABLE || 'true' }}
  RUN_TESTS: ${{ github.event.inputs.RUN_TESTS || 'true' }}
  NODEJS_VERSION: 24
  FUNCTION_1_NAME: student-application-health-check
  FUNCTION_1_REPOSITORY_PATH: health-check
  FUNCTION_2_NAME: student-application-auth-module
  FUNCTION_2_REPOSITORY_PATH: auth-module
  FUNCTION_3_NAME: student-application-user-info
  FUNCTION_3_REPOSITORY_PATH: user-info
  FUNCTION_REPOSITORY_PATH: null
  DEV_ENVIRONMENT_SOURCE_FILE: env/env-dev
  ENVIRONMENT_TEMP_FILE: /tmp/env-lambda.json
  VERSION_FILE: package.json
  LAMBDA_DEPLOYMENT_PACKAGE: lambda.zip
  AWS_REGION: ap-southeast-1
  AWS_OIDC_ROLE_ARN: arn:aws:iam::104322896078:role/CustomRoleLambdaGithubCodeDeploy
  AWS_ALLOWED_ACCOUNT_IDS: 104322896078

jobs:
  deploy:
    name: Deploy Lambda function
    runs-on: ubuntu-latest

    steps:
        # Set parameters based on the selected function.
      - name: Set function parameters
        run: |
          if [[ "${INPUT_FUNCTION}" == "function-1" ]]; then
            echo "Selected function-1"
            echo "LAMBDA_FUNCTION_NAME=${{ env.FUNCTION_1_NAME }}" >> $GITHUB_ENV
            echo "Lambda function name: ${LAMBDA_FUNCTION_NAME}"

            echo "FUNCTION_REPOSITORY_PATH=${{ env.FUNCTION_1_REPOSITORY_PATH }}" >> $GITHUB_ENV
            echo "Lambda function repository path: ${FUNCTION_REPOSITORY_PATH}"
          elif [[ "${INPUT_FUNCTION}" == "function-2" ]]; then
            echo "Selected function-2"
            echo "LAMBDA_FUNCTION_NAME=${{ env.FUNCTION_2_NAME }}" >> $GITHUB_ENV
            echo "Lambda function name: ${LAMBDA_FUNCTION_NAME}"

            echo "FUNCTION_REPOSITORY_PATH=${{ env.FUNCTION_2_REPOSITORY_PATH }}" >> $GITHUB_ENV
            echo "Lambda function repository path: ${FUNCTION_REPOSITORY_PATH}"
          else
            echo "Invalid function selection: "${INPUT_FUNCTION}""
            exit 1
          fi
 
        # Validate dependencies.
      - name: Validate dependencies
        run: |
          echo "AWS OIDC role ARN: ${AWS_OIDC_ROLE_ARN}"
          echo "AWS role allowed account IDs: ${AWS_ALLOWED_ACCOUNT_IDS}"
          echo "AWS CLI version: $(aws --version)"

        # Checkout the code repository.
      - name: Repository checkout
        uses: actions/checkout@v5
        with:
          clean: true      #Cleans the workspace before checking out code.
          fetch-depth: 0   #Required to push back

        # Setup the Nodejs environment.
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.FUNCTION_REPOSITORY_PATH }}

        # Check the Nodejs version.
      - name: Check Nodejs
        run: |
          echo "Expected nodejs version: ${NODEJS_VERSION}"
          echo "Installed nodejs version: $(node -v)"
          echo "Installed npm version: $(npm -v)"

        # Install nodejs dependencies.
      - name: Install dependencies
        if: ${{ env.RUN_TESTS == 'false' }}
        run: | 
          cd ${FUNCTION_REPOSITORY_PATH}
          npm ci --omit=dev

        # Create the Lambda deployment package.
      - name: Create Lambda deployment package
        run: |
          cd ${FUNCTION_REPOSITORY_PATH}
          # Exclude unnecessary files and directories from the deployment package.
          zip -r "${LAMBDA_DEPLOYMENT_PACKAGE}" . -x ".git/*" ".github/*" "test/*" "${LAMBDA_DEPLOYMENT_PACKAGE}"

          # Validate deployment file creation.
          if [ ! -f "${LAMBDA_DEPLOYMENT_PACKAGE}" ]; then
            echo "Error: Deployment package not created!"
            exit 1
          elif [ ! -s "${LAMBDA_DEPLOYMENT_PACKAGE}" ]; then
            echo "Error: Deployment package is empty!"
            exit 1
          else
            ls -la | grep "${LAMBDA_DEPLOYMENT_PACKAGE}"
          fi

        # Configure AWS credentials using GitHub OIDC.
      - name: Configure AWS credentials
        if: ${{ env.INPUT_ACTION == 'build-and-deploy' }}
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          allowed-account-ids: ${{ env.AWS_ALLOWED_ACCOUNT_IDS }}

        # Deploy code to the existing Lambda function.
      - name: Deploy code to Lambda function
        if: ${{ env.INPUT_ACTION == 'build-and-deploy' }}
        run: |
          cd ${FUNCTION_REPOSITORY_PATH}
          aws lambda update-function-code --function-name "${LAMBDA_FUNCTION_NAME}" --zip-file "fileb://${LAMBDA_DEPLOYMENT_PACKAGE}" --publish \
          --query '{FunctionName:FunctionName,Version:Version,CodeSha256:CodeSha256}' --output table

        # Wait until the Lambda function has finished updating with the new code.
      - name: Wait for Lambda function to update
        if: ${{ env.INPUT_ACTION == 'build-and-deploy' }}
        run: |
          aws lambda wait function-updated --function-name "${LAMBDA_FUNCTION_NAME}"

        # Read the Lambda environment file and convert it to JSON format for for the AWS CLI.
      - name: Read Lambda environment file
        if: ${{ env.INPUT_ACTION == 'build-and-deploy' }}
        run: |
          set -euo pipefail
          ENV_FILE="${FUNCTION_REPOSITORY_PATH}/${DEV_ENVIRONMENT_SOURCE_FILE}"

          ENV_JSON=$(
            jq -Rn '
              reduce (inputs | select(length > 0 and (startswith("#") | not)) | capture("^(?<key>[A-Za-z_][A-Za-z0-9_]*)=(?<value>.*)$")) as $env
              ({}; .[$env.key] = $env.value)
            ' < "$ENV_FILE"
          )

          # Check if the JSON is valid and save it to a temporary file.
          echo "$ENV_JSON" | jq empty
          echo "$ENV_JSON" > "${ENVIRONMENT_TEMP_FILE}"

          # Display the variables for debugging
          echo "Extracted environment variables:"
          cat "${ENVIRONMENT_TEMP_FILE}"

        # Update the Lambda function's environment variables.
      - name: Update Lambda environment variables
        if: ${{ env.INPUT_ACTION == 'build-and-deploy' }}
        run: |
          aws lambda update-function-configuration --function-name "${LAMBDA_FUNCTION_NAME}" --environment "Variables=$(cat /tmp/lambda-env.json)"

        # Wait until the Lambda function has finished updating with the new environment variables.
      - name: Wait for Lambda function to update
        if: ${{ env.INPUT_ACTION == 'build-and-deploy' }}
        run: |
          aws lambda wait function-updated --function-name "${LAMBDA_FUNCTION_NAME}"

        # Display information of the updated Lambda function.
      - name: Show Lambda information
        if: ${{ env.INPUT_ACTION == 'build-and-deploy' }}
        run: |
          aws lambda get-function --function-name "${LAMBDA_FUNCTION_NAME}" --query \
          'Configuration.{
              FunctionName: FunctionName,
              Runtime: Runtime,
              Version: Version,
              LastModified: LastModified,
              CodeSize: CodeSize
            }' --output table